# Generated by Django 3.0.4 on 2020-10-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='address',
            field=models.CharField(blank=True, max_length=111, null=True),
        ),
    ]
