# Generated by Django 3.0.4 on 2020-10-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_cart', '0002_orderupdate_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, max_length=111, null=True),
        ),
    ]
